### ISSUE TITLE
[Request] Optional Tinkers Compatibility

### ISSUE THREAD

**Issue by Zsashas** [EmoKiba/Baubley-Heart-Canisters#1]
Mainly the Wither Bones, since Tinkers has their own Necrotic Bones still, could those be compatible with the recipes? Maybe alternate recipes that only load if TiCon is detected?

**Comment by EmoKiba** [comment]
It’s already in the new update I’m just working on the release ... if tinkers is loaded the wither bones don’t drop and the recipe works with narcotic bones
