### ISSUE TITLE
[Suggestion] Configs to disable it as drops from all mobs?

### ISSUE THREAD

**Issue by Vyraal1** [EmoKiba/Baubley-Heart-Canisters#2]
I briefly tried looking through my config folder and didn't notice a file or folder that was named either "BHC" or "Baubley Heart Canisters" so I'm working off the assumption one isn't generated, apologies if this is wrong.

I tried checking various mod loot tables using LootTweaker but wasn't able to find any additions of heart drops with the /mt loottable all command, so I'm not even sure if CraftTweaker or its more feature-rich alternative in LootTweaker can even disable these drops. 

Possible ways to implement the configs could be an entity blacklist? Players could just copy and paste the registry entity id of the mob they want to blacklist it from. At minimum a boolean to disable heart drops would be very much appreciated - that way the modpack dev can just then use LootTweaker to add the heart drops to each particular mob by themselves.

Btw thanks for re-implementing this, I always thought that the hard cap limit of only 10 hearts could affect how mob/combat progression in minecraft worked, so this gives a lot more flexibility.

**Comment by EPIICTHUNDERCAT** [comment]
did you run the game to generate the config? IF you did, we will look into it :)

**Comment by EmoKiba** [comment]
There isn’t a way to configure what drops them however the dropRate is completely configurable this can be done in game or in the config folder

**Comment by EmoKiba** [comment]
Vyraal1 are you on the latest build?

**Comment by Vyraal1** [comment]
Sorry for the delay, yeah updating it to the latest build had the config drop rates I was looking for, thanks!
