### ISSUE TITLE
heart canisters of the same type stack for adding hitpoints

### ISSUE THREAD

**Issue by majijn** [EmoKiba/Baubley-Heart-Canisters#3]
![2017-12-10_16 44 06](https://user-images.githubusercontent.com/18368034/33818199-d43a6eea-de43-11e7-8f41-b4262fe568bb.png)

**Comment by UpcraftLP** [comment]
fixed in [v1.1.0](https://minecraft.curseforge.com/projects/baubley-heart-canisters/files/2508782 "CurseForge Download") :)
