### ISSUE TITLE
Config option to make the Heart Amulet a "Baubles Trinket"

### ISSUE THREAD

**Issue by kd8lvt** [EmoKiba/Baubley-Heart-Canisters#5]
I feel this would be a great option to add, because Thaumcraft's "Amulet of Vis" bauble takes up the amulet bauble slot. The Amulet of Vis is one of the best baubles to have within Thaumcraft, due to it's main purpose - recharging items that use Vis, (such as the Boots of the Traveler) without you having to run home and recharge them every few minutes. Problem being, the Heart Amulet conflicts with the Amulet of Vis, taking up the Amulet slot as well.

Having the ability to equip both would be great, not to mention, making it a configuration option would give modpack developers the choice of disabling this feature, if they feel it is overpowered, or enabling it, if they desire the flexibility.

**Comment by Radient-Sora** [comment]
Fixed [here](https://github.com/Radient-Sora/Baubley-Heart-Canisters/commit/01570bc29a1346f2ff4cd397825c6827eba4e85d)
