### ISSUE TITLE
[1.21] Smelting Recipes For Hearts Are Wrong

### ISSUE THREAD

**Issue by UnknownSerhan** [EmoKiba/Baubley-Heart-Canisters#74]
Discussed on discord, the smelting recipes for hearts are wrong.

![image](https://github.com/user-attachments/assets/8ce68b43-ff64-4ba2-b4b0-f6347804d87d)
![image](https://github.com/user-attachments/assets/d8e33582-7c25-4f9c-aa68-fa7bc9833599)
![image](https://github.com/user-attachments/assets/22753058-ca90-4888-baa9-fb075f02d07a)

**Comment by Mrbysco** [comment]
This issue was resolved in commit https://github.com/Traverse-Joe/Baubley-Heart-Canisters/commit/39c7b1805bb4a449f8094dcaa62685b0520f2b41 which is on CurseForge/Modrinth (v1.1.1)
