### ISSUE TITLE
[1.21] Soul Amulet GUI is a Bit Broken

### ISSUE THREAD

**Issue by UnknownSerhan** [EmoKiba/Baubley-Heart-Canisters#76]
https://github.com/user-attachments/assets/060d63df-7c55-49cb-b0a5-56e4d3bc02bc

**Comment by Mrbysco** [comment]
This issue has been fixed in 1.2.1 which is available on CurseForge and Modrinth
https://www.curseforge.com/minecraft/mc-mods/baubley-heart-canisters/files/6040943
