### ISSUE TITLE
[Feature Request] Disable Drops Via Config

### ISSUE THREAD

**Issue by Darkosto** [EmoKiba/Baubley-Heart-Canisters#77]
Hey Traverse Joe!

I've been working on getting BHC integrated into my pack and noticed when using a mod like Just Enough Resources, your loot injection must be happening a bit later on for it to show on this GUI: 
![image](https://github.com/user-attachments/assets/55f20515-14fc-470a-9556-777d2a40a0db)

Would it be possible for you to allow a config option to disable drops from BHC so I can reimplement them via datapacks or Crafttweaker which would appear in these GUIs? I'm hoping I can give players as much info as possible.

Thanks so much and I hope you're doing well!!
Darkosto

MC: 1.20.1
Forge: 47.3.0
BHC: 1.0.5

**Comment by Traverse-Joe** [comment]
Hey Darko the drops config should allow this by setting them to 0 , if that doesn't work I plan to implement the drops via datapack its just been hard to find free time if you have more questions I’m always around in discord
